# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='compartido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tecnico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='web.Tecnico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nodo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
