# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171117_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='compartido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
